#! /bin/bash

if [[ ! -e $1 ]]; then
	echo Usage: $0 input-file
	exit 1
fi

BASE=$1
BASE=${BASE#input-}
BASE=${BASE%.txt}

./input_helper ./input/input-$BASE.txt query-$BASE.pl
swipl < query-$BASE.pl > prolog-$BASE.txt
./output_helper ./input/input-$BASE.txt prolog-$BASE.txt output-$BASE.txt
mv query-$BASE.pl ./query
mv prolog-$BASE.txt ./prolog-output
mv output-$BASE.txt ./output


